# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtWidgets, QtCore
import sys

import view.dialog_new_workspace as dnw

app = QtWidgets.QApplication(sys.argv)

# try:
#     with open( "fffffffffff.txt" ) as f :
#         pass
# except Exception as e: # parent of IOError, OSError *and* WindowsError where available
#     print('aaaaaa')
#     print(e)
with open( "fffffffffff.txt" ) as f :
    pass

d = dnw.DialogNewWorkspace()
if d.exec():
    params = d.getParams()
    print(params)
else:
    print('cancel')

sys.exit(app.exec())
