# Form implementation generated from reading ui file 'dialog_new_workspace.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogNewWorkspace(object):
    def setupUi(self, DialogNewWorkspace):
        DialogNewWorkspace.setObjectName("DialogNewWorkspace")
        DialogNewWorkspace.resize(600, 150)
        DialogNewWorkspace.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(DialogNewWorkspace)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelWorkspaceName = QtWidgets.QLabel(DialogNewWorkspace)
        self.labelWorkspaceName.setObjectName("labelWorkspaceName")
        self.gridLayout.addWidget(self.labelWorkspaceName, 0, 0, 1, 1)
        self.lineEditWorkspaceName = QtWidgets.QLineEdit(DialogNewWorkspace)
        self.lineEditWorkspaceName.setObjectName("lineEditWorkspaceName")
        self.gridLayout.addWidget(self.lineEditWorkspaceName, 0, 1, 1, 1)
        self.labelWorkspaceDirectory = QtWidgets.QLabel(DialogNewWorkspace)
        self.labelWorkspaceDirectory.setObjectName("labelWorkspaceDirectory")
        self.gridLayout.addWidget(self.labelWorkspaceDirectory, 1, 0, 1, 1)
        self.lineEditWorkspaceDirectory = QtWidgets.QLineEdit(DialogNewWorkspace)
        self.lineEditWorkspaceDirectory.setReadOnly(True)
        self.lineEditWorkspaceDirectory.setObjectName("lineEditWorkspaceDirectory")
        self.gridLayout.addWidget(self.lineEditWorkspaceDirectory, 1, 1, 1, 1)
        self.pushButtonChooseWorkspaceDirectory = QtWidgets.QPushButton(DialogNewWorkspace)
        self.pushButtonChooseWorkspaceDirectory.setObjectName("pushButtonChooseWorkspaceDirectory")
        self.gridLayout.addWidget(self.pushButtonChooseWorkspaceDirectory, 1, 2, 1, 1)
        self.labelWorkspaceExportDirectory = QtWidgets.QLabel(DialogNewWorkspace)
        self.labelWorkspaceExportDirectory.setObjectName("labelWorkspaceExportDirectory")
        self.gridLayout.addWidget(self.labelWorkspaceExportDirectory, 2, 0, 1, 1)
        self.lineEditWorkspaceExportDirectory = QtWidgets.QLineEdit(DialogNewWorkspace)
        self.lineEditWorkspaceExportDirectory.setReadOnly(True)
        self.lineEditWorkspaceExportDirectory.setObjectName("lineEditWorkspaceExportDirectory")
        self.gridLayout.addWidget(self.lineEditWorkspaceExportDirectory, 2, 1, 1, 1)
        self.pushButtonChooseWorkspaceExportDirectory = QtWidgets.QPushButton(DialogNewWorkspace)
        self.pushButtonChooseWorkspaceExportDirectory.setObjectName("pushButtonChooseWorkspaceExportDirectory")
        self.gridLayout.addWidget(self.pushButtonChooseWorkspaceExportDirectory, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogNewWorkspace)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(DialogNewWorkspace)
        self.buttonBox.accepted.connect(DialogNewWorkspace.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogNewWorkspace.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogNewWorkspace)

    def retranslateUi(self, DialogNewWorkspace):
        _translate = QtCore.QCoreApplication.translate
        DialogNewWorkspace.setWindowTitle(_translate("DialogNewWorkspace", "新建工作区"))
        self.labelWorkspaceName.setText(_translate("DialogNewWorkspace", "工作区名字："))
        self.labelWorkspaceDirectory.setText(_translate("DialogNewWorkspace", "工作区位置："))
        self.pushButtonChooseWorkspaceDirectory.setText(_translate("DialogNewWorkspace", "浏览..."))
        self.labelWorkspaceExportDirectory.setText(_translate("DialogNewWorkspace", "导出位置："))
        self.pushButtonChooseWorkspaceExportDirectory.setText(_translate("DialogNewWorkspace", "浏览..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogNewWorkspace = QtWidgets.QDialog()
    ui = Ui_DialogNewWorkspace()
    ui.setupUi(DialogNewWorkspace)
    DialogNewWorkspace.show()
    sys.exit(app.exec())
