pyuic6 -x widget_action_property.ui -o widget_action_property.py
pyuic6 -x widget_assignment_property.ui -o widget_assignment_property.py
pyuic6 -x widget_calculate_property.ui -o widget_calculate_property.py
pyuic6 -x widget_common_property_comment.ui -o widget_common_property_comment.py
pyuic6 -x widget_common_property_debug.ui -o widget_common_property_debug.py
pyuic6 -x widget_condition_property.ui -o widget_condition_property.py
pyuic6 -x widget_default_property.ui -o widget_default_property.py
pyuic6 -x widget_empty_property.ui -o widget_empty_property.py
pyuic6 -x widget_example_property.ui -o widget_example_property.py
pyuic6 -x widget_finish_property.ui -o widget_finish_property.py
pyuic6 -x widget_subtree_property.ui -o widget_subtree_property.py
pyuic6 -x widget_probabilistic_choice_property.ui -o widget_probabilistic_choice_property.py
pyuic6 -x widget_wait_property.ui -o widget_wait_property.py
pyuic6 -x widget_common_property_empty.ui -o widget_common_property_empty.py
pyuic6 -x widget_weight_property.ui -o widget_weight_property.py
pyuic6 -x dialog_new_workspace.ui -o dialog_new_workspace.py
pyuic6 -x dialog_export.ui -o dialog_export.py
pyuic6 -x main_window.ui -o main_window.py
pyuic6 -x dialog_scene_setting.ui -o dialog_scene_setting.py