# Form implementation generated from reading ui file 'widget_common_property_comment.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(260, 96)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBoxComment = QtWidgets.QGroupBox(Form)
        self.groupBoxComment.setObjectName("groupBoxComment")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBoxComment)
        self.formLayout_2.setObjectName("formLayout_2")
        self.labelComment = QtWidgets.QLabel(self.groupBoxComment)
        self.labelComment.setObjectName("labelComment")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelComment)
        self.lineEditComment = QtWidgets.QLineEdit(self.groupBoxComment)
        self.lineEditComment.setObjectName("lineEditComment")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditComment)
        self.labelColor = QtWidgets.QLabel(self.groupBoxComment)
        self.labelColor.setObjectName("labelColor")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelColor)
        self.comboBoxColor = QtWidgets.QComboBox(self.groupBoxComment)
        self.comboBoxColor.setObjectName("comboBoxColor")
        self.comboBoxColor.addItem("")
        self.comboBoxColor.addItem("")
        self.comboBoxColor.addItem("")
        self.comboBoxColor.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBoxColor)
        self.gridLayout.addWidget(self.groupBoxComment, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBoxComment.setTitle(_translate("Form", "注释"))
        self.labelComment.setText(_translate("Form", "注释"))
        self.labelColor.setText(_translate("Form", "背景颜色"))
        self.comboBoxColor.setItemText(0, _translate("Form", "NoColor"))
        self.comboBoxColor.setItemText(1, _translate("Form", "Red"))
        self.comboBoxColor.setItemText(2, _translate("Form", "Yellow"))
        self.comboBoxColor.setItemText(3, _translate("Form", "Blue"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
