# Form implementation generated from reading ui file 'widget_subtree_property.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(137, 70)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBoxProperty = QtWidgets.QGroupBox(Form)
        self.groupBoxProperty.setObjectName("groupBoxProperty")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxProperty)
        self.formLayout.setObjectName("formLayout")
        self.labelSubTree = QtWidgets.QLabel(self.groupBoxProperty)
        self.labelSubTree.setObjectName("labelSubTree")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelSubTree)
        self.comboBoxSubTree = QtWidgets.QComboBox(self.groupBoxProperty)
        self.comboBoxSubTree.setObjectName("comboBoxSubTree")
        self.comboBoxSubTree.addItem("")
        self.comboBoxSubTree.setItemText(0, "")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboBoxSubTree)
        self.gridLayout.addWidget(self.groupBoxProperty, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBoxProperty.setTitle(_translate("Form", "属性"))
        self.labelSubTree.setText(_translate("Form", "子树"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
