# Form implementation generated from reading ui file 'widget_common_property_debug.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(213, 70)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBoxDebug = QtWidgets.QGroupBox(Form)
        self.groupBoxDebug.setObjectName("groupBoxDebug")
        self.formLayout = QtWidgets.QFormLayout(self.groupBoxDebug)
        self.formLayout.setObjectName("formLayout")
        self.labelID = QtWidgets.QLabel(self.groupBoxDebug)
        self.labelID.setObjectName("labelID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelID)
        self.lineEditID = QtWidgets.QLineEdit(self.groupBoxDebug)
        self.lineEditID.setReadOnly(True)
        self.lineEditID.setObjectName("lineEditID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineEditID)
        self.gridLayout.addWidget(self.groupBoxDebug, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBoxDebug.setTitle(_translate("Form", "调试"))
        self.labelID.setText(_translate("Form", "节点ID"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
